name: Speakwize
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - python
  - pip
  - ipython
  - jupyter
  - google-colab
  - pandas
  - pip:
    - yt-dlp
    - git+https://github.com/m-bain/whisperx.git
    - supabase