name: cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 19 ]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: frontend  # Update the working directory

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cloudflare

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
        working-directory: frontend  # Update the working directory

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: cloudflare
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          NODE_VERSION: ${{ vars.NODE_VERSION }}
        working-directory: frontend  # Update the working directory

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: frontend  # Update the working directory for the Wrangler action
        env:
          NITRO_PRESET: cloudflare
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          NODE_VERSION: ${{ vars.NODE_VERSION }}