name: cloudflare-dev

on:
  push:
    branches:
      - 'dev/*'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 19 ]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: frontend

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cloudflare

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
        working-directory: frontend

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: cloudflare
        working-directory: frontend

      - name: Publish to Cloudflare Dev
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: frontend
          environment: 'dev'
